const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const storedPlaces=JSON.parse(localStorage.getItem('sgc-places')||'{}');
if(!storedPlaces.hotel && localStorage.getItem('sgc-hotel')) storedPlaces.hotel=localStorage.getItem('sgc-hotel');
const state={mode:localStorage.getItem('sgc-mode')||'resident',lat:null,lon:null,nearby:null,rail:null,train:null,traffic:null,weather:null,places:{home:storedPlaces.home||'',work:storedPlaces.work||'',hotel:storedPlaces.hotel||''}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function greet(){const h=new Date().getHours();$('#greeting').textContent=h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function sourceLabel(){const sources=[state.nearby?.source,state.rail?.source,state.train?.source,state.traffic?.source,state.weather?.source].filter(Boolean);const live=sources.some(x=>x==='live');const demo=sources.some(x=>String(x).startsWith('demo'));$('#sourceBadge').textContent=live&&!demo?'LIVE GOVERNMENT DATA':live?'MIXED LIVE + DEMO':'DEMO MODE';$('#updatedAt').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
const loadText=x=>x==='SEA'?'Seats':x==='SDA'?'Standing':x==='LSD'?'Crowded':'—';
const lineClass=line=>'line-'+String(line||'rail').toLowerCase().replace(/[^a-z0-9]/g,'');
function renderStop(stop){return `<article class="card stop-card"><div class="stop-top"><div><div class="stop-name">${esc(stop.name)}</div><div class="stop-code">Stop ${esc(stop.code)}</div></div>${stop.distance!=null?`<div class="distance">${stop.distance<1000?stop.distance+' m':(stop.distance/1000).toFixed(1)+' km'}</div>`:''}</div><div class="services">${(stop.services||[]).slice(0,8).map(s=>`<div class="service"><div class="service-no">${esc(s.no)}</div><div class="eta">${s.eta?.[0]??'—'} <small>min</small></div><div class="load">${loadText(s.load?.[0])}</div></div>`).join('')||'<span class="distance">No estimated arrivals right now.</span>'}</div></article>`}
function renderNearby(){const stops=state.nearby?.stops||[];$('#nearbyStops').innerHTML=stops.map(renderStop).join('')||'<div class="card empty">No nearby bus stops found.</div>';sourceLabel()}
function groupedDepartures(station){const groups=new Map();for(const d of station.departures||[]){const key=`${d.line}|${d.destination}|${d.platform||''}`;if(!groups.has(key))groups.set(key,{...d,etas:[]});groups.get(key).etas.push(d.minutes)}return [...groups.values()].slice(0,6)}
function renderRail(){const stations=state.rail?.stations||[];$('#railStations').innerHTML=stations.map(station=>`<article class="card rail-card"><div class="stop-top"><div><div class="stop-name">${esc(station.name)}</div><div class="stop-code">${esc((station.codes||[]).join(' · '))}</div></div>${station.distance!=null?`<div class="distance">${station.distance<1000?station.distance+' m':(station.distance/1000).toFixed(1)+' km'}</div>`:''}</div><div class="train-list">${groupedDepartures(station).map(d=>`<div class="train-row"><div class="line-badge ${lineClass(d.line)}">${esc(d.line)}</div><div class="train-dest"><strong>${esc(d.destination)}</strong><span>${d.platform?`Platform ${esc(d.platform)} · `:''}${esc(d.lineName||'Train')}</span></div><div class="train-times">${d.etas.slice(0,3).map((m,i)=>`<span class="${i===0?'next':''}">${m===0?'Arr':m+'m'}</span>`).join('')}</div></div>`).join('')||'<div class="empty-inline">No predicted departures in the next 90 minutes.</div>'}</div></article>`).join('')||'<div class="card empty">No rail station found.</div>';sourceLabel()}
function renderAlerts(){const a=[];if(state.train){if(state.train.status===2)(state.train.disruptions||[]).forEach(d=>a.push({i:'⚠',t:`${d.line||'Rail'} disruption`,c:d.message||'Service disruption'}));else a.push({i:'✓',t:'Rail network normal',c:'No major train service disruption reported.'})}if(state.traffic){(state.traffic.incidents||[]).slice(0,3).forEach(x=>a.push({i:'⌁',t:x.type||'Traffic incident',c:x.message||'Road incident reported.'}))}$('#alerts').innerHTML=a.map(x=>`<div class="card alert"><div class="alert-icon">${x.i}</div><div><div class="alert-title">${esc(x.t)}</div><div class="alert-copy">${esc(x.c)}</div></div></div>`).join('')||'<div class="card">No alerts loaded.</div>'}
function updateHero(){const w=state.weather;$('#weatherMetric').textContent=w?'☁︎':'—';$('#weatherLabel').textContent=w?.summary||'Weather';$('#railMetric').textContent=state.train?(state.train.status===2?'⚠':'✓'):'—';$('#trafficMetric').textContent=state.traffic?.count??'—';renderAlerts();sourceLabel()}
async function json(url){const r=await fetch(url);const p=await r.json();if(!r.ok)throw new Error(p.error||`Request failed ${r.status}`);return p}
async function refreshContext(){try{const [train,traffic,weather]=await Promise.all([json('/api/train'),json('/api/traffic'),json('/api/weather')]);Object.assign(state,{train,traffic,weather});updateHero()}catch(e){toast(e.message)}}
async function loadNearby(lat,lon){const busPromise=json(`/api/nearby?lat=${lat}&lon=${lon}`).then(p=>{state.nearby=p;renderNearby()}).catch(e=>toast('Bus: '+e.message));const railPromise=json(`/api/rail?lat=${lat}&lon=${lon}`).then(p=>{state.rail=p;renderRail()}).catch(e=>toast('MRT: '+e.message));await Promise.all([busPromise,railPromise])}
async function locate(){if(!navigator.geolocation){toast('Location is not supported on this device.');return}$('#placeLabel').textContent='Locating…';navigator.geolocation.getCurrentPosition(async p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;$('#placeLabel').textContent='Near you';await loadNearby(state.lat,state.lon)},()=>{$('#placeLabel').textContent='Singapore';toast('Location permission was not granted. Search a station or bus stop instead.')},{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
async function checkStop(code){try{const p=await json('/api/bus?stop='+encodeURIComponent(code));state.nearby={source:p.source,stops:[p.stop]};renderNearby();$('#nearbyStops').scrollIntoView({behavior:'smooth',block:'center'})}catch(e){toast(e.message)}}
async function checkRail(query){try{const p=await json('/api/rail?station='+encodeURIComponent(query));state.rail=p;renderRail();$('#railStations').scrollIntoView({behavior:'smooth',block:'center'})}catch(e){toast(e.message)}}
function firstRail(){return state.rail?.stations?.[0]?.departures?.slice().sort((a,b)=>a.minutes-b.minutes)?.[0]}
function firstBus(){return state.nearby?.stops?.[0]?.services?.map(s=>({no:s.no,minutes:s.eta?.[0]})).filter(x=>x.minutes!=null).sort((a,b)=>a.minutes-b.minutes)?.[0]}
function advisor(q){const text=q.toLowerCase();let reply='I can use Singapore MRT, bus, weather and disruption data. Try “When is my next train?”, “Should I leave now?” or “Is it raining?”';const rail=firstRail(),bus=firstBus();if(/next.*train|mrt.*time|train.*time/.test(text))reply=rail?`From ${state.rail.stations[0].name}, the next ${rail.line} train towards ${rail.destination} is about ${rail.minutes} minute${rail.minutes===1?'':'s'} away${rail.platform?` from platform ${rail.platform}`:''}.`:'Search or locate an MRT station first, then I can tell you the next trains.';else if(/train|mrt|rail/.test(text))reply=state.train?.status===2?`There is a rail disruption: ${state.train.disruptions?.[0]?.message||'check the alert below.'}`:rail?`Rail service is currently normal. Your next nearby train is ${rail.line} towards ${rail.destination} in about ${rail.minutes} minutes.`:'No major train disruption is currently reported.';else if(/rain|weather|umbrella/.test(text))reply=`Current forecast: ${state.weather?.summary||'weather data is not loaded yet'}.`;else if(/leave|next.*bus|bus.*time/.test(text)){const candidates=[];if(bus)candidates.push({mode:`bus ${bus.no}`,minutes:bus.minutes});if(rail)candidates.push({mode:`${rail.line} train`,minutes:rail.minutes});candidates.sort((a,b)=>a.minutes-b.minutes);reply=candidates[0]?`The soonest nearby departure I can see is ${candidates[0].mode} in about ${candidates[0].minutes} minutes. ${candidates[0].minutes<=5?'I would head out now.':'You have a little time, but refresh before leaving.'}`:'Locate yourself or search a stop/station first, then I can make that call.'}$('#advisorReply').textContent=reply}
function setMode(mode){state.mode=mode;localStorage.setItem('sgc-mode',mode);$('#modeText').textContent=mode==='traveller'?'Traveller':'Resident';$('#travellerPanel').classList.toggle('hidden',mode!=='traveller');$('#modeButton .dot').style.background=mode==='traveller'?'#79a7ff':'';updateHotelButton()}
function initPlaces(){for(const key of ['home','work','hotel'])$(`#${key}Input`).value=state.places[key]||'';updateHotelButton()}
function savePlaces(){state.places={home:$('#homeInput').value.trim(),work:$('#workInput').value.trim(),hotel:$('#hotelInput').value.trim()};localStorage.setItem('sgc-places',JSON.stringify(state.places));localStorage.setItem('sgc-hotel',state.places.hotel||'');updateHotelButton();toast('Places saved on this device')}
function updateHotelButton(){$('#goHotelButton').disabled=!state.places.hotel}
function openTransit(destination,origin=''){if(!destination)return toast('Add a destination first.');const u=new URL('https://www.google.com/maps/dir/');u.searchParams.set('api','1');u.searchParams.set('destination',destination);u.searchParams.set('travelmode','transit');if(origin)u.searchParams.set('origin',origin);window.open(u.toString(),'_blank','noopener')}
$('#locateButton').addEventListener('click',locate);$('#refreshButton').addEventListener('click',async()=>{await refreshContext();if(state.lat!=null&&state.lon!=null)await loadNearby(state.lat,state.lon);else{if(state.rail?.stations?.[0]?.codes?.[0])await checkRail(state.rail.stations[0].codes[0]);if(state.nearby?.stops?.[0]?.code)await checkStop(state.nearby.stops[0].code)}toast('Refreshed')});
$('#stopForm').addEventListener('submit',e=>{e.preventDefault();const c=$('#stopInput').value.trim();if(!/^\d{5}$/.test(c))return toast('Enter a 5-digit bus stop code.');checkStop(c)});$('#railForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#railInput').value.trim();if(!q)return toast('Enter a station name or code.');checkRail(q)});
$('#advisorForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#advisorInput').value.trim();if(q)advisor(q)});$$('.chips button').forEach(b=>b.addEventListener('click',()=>advisor(b.dataset.q)));
$('#modeButton').addEventListener('click',()=>setMode(state.mode==='resident'?'traveller':'resident'));$('#navTravel').addEventListener('click',()=>{setMode('traveller');$('#travellerPanel').scrollIntoView({behavior:'smooth'})});$('#navFreya').addEventListener('click',()=>$('#advisorInput').focus());$('#navTransport').addEventListener('click',()=>$('#railStations').scrollIntoView({behavior:'smooth'}));
$('#savePlaces').addEventListener('click',savePlaces);$$('.quick-destinations button').forEach(b=>b.addEventListener('click',()=>{const value=state.places[b.dataset.place]||'';if(!value)return toast(`Save your ${b.dataset.place} first.`);$('#tripTo').value=value}));$('#planTrip').addEventListener('click',()=>openTransit($('#tripTo').value.trim(),$('#tripFrom').value.trim()));$('#goHotelButton').addEventListener('click',()=>openTransit(state.places.hotel));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
greet();setMode(state.mode);initPlaces();refreshContext();checkRail('EW4');checkStop('84009');
