const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const safeParse=(value,fallback)=>{try{return JSON.parse(value)}catch{return fallback}};
const storedPlaces=safeParse(localStorage.getItem('sgc-places')||'{}',{});
if(!storedPlaces.hotel && localStorage.getItem('sgc-hotel')) storedPlaces.hotel=localStorage.getItem('sgc-hotel');
const storedStops=safeParse(localStorage.getItem('sgc-bus-stops')||'[]',[]);
const storedStations=safeParse(localStorage.getItem('sgc-rail-stations')||'[]',[]);
const state={
  mode:localStorage.getItem('sgc-mode')||'resident',
  transportView:localStorage.getItem('sgc-transport-view')||'cards',
  lat:null,lon:null,nearby:null,rail:null,train:null,traffic:null,weather:null,
  places:{home:storedPlaces.home||'',work:storedPlaces.work||'',hotel:storedPlaces.hotel||''},
  savedStops:Array.isArray(storedStops)?storedStops.filter(x=>x&&/^\d{5}$/.test(String(x.code||x))).map(x=>({code:String(x.code||x),name:x.name||'',services:Array.isArray(x.services)?x.services.map(String):[]})).slice(0,20):[],
  savedStopData:[],
  savedRailStations:Array.isArray(storedStations)?storedStations.map(x=>typeof x==='string'?{code:x,name:''}:x).filter(x=>x?.code).map(x=>({code:String(x.code).toUpperCase(),name:x.name||''})).slice(0,12):[],
  savedRailData:[],
  locationChoice:localStorage.getItem('sgc-location-choice')||'',
  profileToken:localStorage.getItem('sgc-profile-token')||'',
  profile:null,
  cloudStatus:'local',
  map:null,mapLayer:null
};
let deferredInstallPrompt=null;
let profileSyncTimer=null;
let pairLink='';
let pairQrObjectUrl='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function greet(){const h=new Date().getHours();$('#greeting').textContent=h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

function persistentPreferences(){return {savedBusStops:state.savedStops.map(({code,name,services})=>({code,name,services:Array.isArray(services)?services:[]})),savedRailStations:state.savedRailStations.map(({code,name})=>({code,name})),places:{...state.places},mode:state.mode}}
function cachePreferences(markDirty=false){localStorage.setItem('sgc-bus-stops',JSON.stringify(state.savedStops.map(({code,name,services})=>({code,name,services:Array.isArray(services)?services:[]}))));localStorage.setItem('sgc-rail-stations',JSON.stringify(state.savedRailStations));localStorage.setItem('sgc-places',JSON.stringify(state.places));localStorage.setItem('sgc-hotel',state.places.hotel||'');localStorage.setItem('sgc-mode',state.mode);if(markDirty)localStorage.setItem('sgc-profile-dirty-at',String(Date.now()))}
function setProfileUi(status,profile=state.profile){state.cloudStatus=status;const badge=$('#profileSyncBadge'),id=$('#profileId'),desc=$('#profileDescription');if(!badge||!id)return;badge.classList.remove('synced','error');if(status==='synced'){badge.textContent='Cloud synced';badge.classList.add('synced')}else if(status==='syncing'){badge.textContent='Syncing…'}else if(status==='pending'){badge.textContent='Pending sync'}else if(status==='error'){badge.textContent='Sync issue';badge.classList.add('error')}else badge.textContent='Local cache';id.textContent=profile?.displayId||'Not linked yet';if(desc){desc.textContent=profile?'Your favourites and saved places are stored in a private SGBuddy cloud profile, with an offline cache on this device.':'Your favourites and saved places can sync privately across your devices without a database or account.'}}
async function profileRequest(method,body){const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(state.profileToken)headers.Authorization='Bearer '+state.profileToken;const r=await fetch('/api/profile',{method,headers,body:body===undefined?undefined:JSON.stringify(body)});let p={};try{p=await r.json()}catch{}if(!r.ok){const e=new Error(p.error||`Profile request failed ${r.status}`);e.status=r.status;throw e}return p}
function applyProfile(profile){if(!profile?.preferences)return;state.profile=profile;const prefs=profile.preferences;state.savedStops=Array.isArray(prefs.savedBusStops)?prefs.savedBusStops.filter(x=>/^\d{5}$/.test(String(x.code||''))).map(x=>({code:String(x.code),name:x.name||'',services:Array.isArray(x.services)?x.services.map(String):[]})).slice(0,20):[];state.savedRailStations=Array.isArray(prefs.savedRailStations)?prefs.savedRailStations.map(x=>typeof x==='string'?{code:x,name:''}:x).filter(x=>x?.code).map(x=>({code:String(x.code).toUpperCase(),name:x.name||''})).slice(0,12):[];state.places={home:prefs.places?.home||'',work:prefs.places?.work||'',hotel:prefs.places?.hotel||''};setMode(prefs.mode||'resident',false);cachePreferences(false);initPlaces();renderSavedStops();renderSavedStations();setProfileUi('synced',profile)}
function consumeProfileHash(){if(!location.hash.startsWith('#'))return false;const params=new URLSearchParams(location.hash.slice(1));const token=params.get('profile');if(!token)return false;state.profileToken=token;localStorage.setItem('sgc-profile-token',token);localStorage.removeItem('sgc-profile-dirty-at');history.replaceState(null,'',location.pathname+location.search);return true}
async function ensureCloudProfile(){if(state.profileToken)return true;setProfileUi('syncing');try{const p=await profileRequest('POST',{preferences:persistentPreferences()});state.profileToken=p.token;state.profile=p.profile;localStorage.setItem('sgc-profile-token',state.profileToken);localStorage.removeItem('sgc-profile-dirty-at');setProfileUi('synced',state.profile);return true}catch(e){setProfileUi('error');return false}}
async function loadCloudProfile(){if(!state.profileToken){setProfileUi('local');return false}setProfileUi('syncing');try{const p=await profileRequest('GET');const dirtyAt=Number(localStorage.getItem('sgc-profile-dirty-at')||0);const remoteAt=Date.parse(p.profile?.updatedAt||0)||0;if(dirtyAt>remoteAt){state.profile=p.profile;setProfileUi('pending',state.profile);await syncProfileNow({quiet:true});return true}applyProfile(p.profile);localStorage.removeItem('sgc-profile-dirty-at');return true}catch(e){if(e.status===401){state.profileToken='';state.profile=null;localStorage.removeItem('sgc-profile-token');setProfileUi('error');toast('This SGBuddy profile link is invalid or expired. Your local cache is still available.')}else setProfileUi('error');return false}}
async function syncProfileNow({quiet=false}={}){if(!(await ensureCloudProfile())){if(!quiet)toast('Cloud sync is unavailable; changes are still saved locally.');return false}setProfileUi('syncing',state.profile);try{const p=await profileRequest('PUT',{preferences:persistentPreferences()});state.profile=p.profile;localStorage.removeItem('sgc-profile-dirty-at');setProfileUi('synced',state.profile);if(!quiet)toast('SGBuddy profile synced');return true}catch(e){setProfileUi('error',state.profile);if(!quiet)toast('Cloud sync failed; your local cache is safe.');return false}}
function queueProfileSync(){cachePreferences(true);setProfileUi(state.profileToken?'pending':'local',state.profile);clearTimeout(profileSyncTimer);profileSyncTimer=setTimeout(()=>syncProfileNow({quiet:true}),650)}
function hasLocalProfileData(){return state.savedStops.length>0||state.savedRailStations.length>0||Object.values(state.places).some(Boolean)}
async function initCloudProfile(){const linked=consumeProfileHash();if(state.profileToken){const ok=await loadCloudProfile();if(ok)await refreshSavedStops();return}if(hasLocalProfileData())await syncProfileNow({quiet:true});else setProfileUi('local');if(linked)toast('SGBuddy profile linked')}

function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function updateInstallUi(){const b=$('#installButton');if(!b)return;if(isStandalone()){b.textContent='✓ Installed';b.classList.add('installed');b.disabled=true}else{b.textContent='⇩ Install app';b.classList.remove('installed');b.disabled=false}}
async function installApp(){if(isStandalone())return;const sheet=$('#installSheet'),instructions=$('#installInstructions');if(deferredInstallPrompt){deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;if(choice?.outcome==='accepted')toast('SGBuddy installed');deferredInstallPrompt=null;updateInstallUi();return}const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);instructions.innerHTML=ios?'On iPhone/iPad: open SGBuddy in <strong>Safari</strong>, tap <strong>Share</strong>, choose <strong>Add to Home Screen</strong>, then tap <strong>Add</strong>.':'Open your browser menu and choose <strong>Install SGBuddy</strong> or <strong>Add to Home screen</strong>.';sheet.classList.remove('hidden')}
function closeInstallSheet(){$('#installSheet').classList.add('hidden')}

async function showPairPanel(){if(!(await ensureCloudProfile()))return;await syncProfileNow({quiet:true});pairLink=`${location.origin}${location.pathname}#profile=${encodeURIComponent(state.profileToken)}`;try{const r=await fetch('/api/profile-qr',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+state.profileToken},body:JSON.stringify({origin:location.origin})});if(!r.ok)throw new Error('Could not make pairing QR');const svg=await r.text();if(pairQrObjectUrl)URL.revokeObjectURL(pairQrObjectUrl);pairQrObjectUrl=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));$('#pairQr').src=pairQrObjectUrl;$('#pairPanel').classList.remove('hidden')}catch(e){toast(e.message)}}
async function copyPairLink(){if(!pairLink)await showPairPanel();try{await navigator.clipboard.writeText(pairLink);toast('Device-link copied')}catch{toast('Could not copy the link on this browser')}}
async function exportProfile(){if(!(await ensureCloudProfile()))return;await syncProfileNow({quiet:true});const payload={type:'sgbuddy-profile',version:1,exportedAt:new Date().toISOString(),warning:'This file contains a secret profile token. Anyone with it can access and change this SGBuddy profile.',token:state.profileToken,profile:state.profile,preferences:persistentPreferences()};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`sgbuddy-${state.profile?.displayId||'profile'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function importProfileFile(file){try{const data=JSON.parse(await file.text());if(!data.token||!String(data.token).startsWith('sgp_'))throw new Error('This is not a valid SGBuddy profile export.');state.profileToken=String(data.token);localStorage.setItem('sgc-profile-token',state.profileToken);localStorage.removeItem('sgc-profile-dirty-at');const ok=await loadCloudProfile();if(ok){await refreshSavedStops();toast('SGBuddy profile imported and linked')}}catch(e){toast(e.message)}}

function sourceLabel(){const sources=[state.nearby?.source,state.rail?.source,state.train?.source,state.traffic?.source,state.weather?.source,...state.savedStopData.map(x=>x.source)].filter(Boolean);const live=sources.some(x=>x==='live');const demo=sources.some(x=>String(x).startsWith('demo'));$('#sourceBadge').textContent=live&&!demo?'LIVE GOVERNMENT DATA':live?'MIXED LIVE + DEMO':'DEMO MODE';$('#updatedAt').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
const loadText=x=>x==='SEA'?'Seats':x==='SDA'?'Standing':x==='LSD'?'Crowded':'—';
const lineClass=line=>'line-'+String(line||'rail').toLowerCase().replace(/[^a-z0-9]/g,'');
const isSaved=code=>state.savedStops.some(s=>s.code===String(code));
const isRailSaved=code=>state.savedRailStations.some(s=>s.code===String(code).toUpperCase());
const savedStopFor=code=>state.savedStops.find(s=>s.code===String(code));
function toggleServicePreference(stopCode,serviceNo){const saved=savedStopFor(stopCode);if(!saved)return toast('Save this bus stop first, then you can pin its services.');saved.services=Array.isArray(saved.services)?saved.services:[];const no=String(serviceNo);const i=saved.services.indexOf(no);if(i>=0)saved.services.splice(i,1);else saved.services.push(no);persistSavedStops(true);renderSavedStops();renderNearby();renderNextUp();toast(i>=0?`Unpinned bus ${no}`:`Pinned bus ${no} for this stop`)}
function renderStop(stop,{compact=false}={}){const saved=isSaved(stop.code),prefs=savedStopFor(stop.code)?.services||[];const services=(stop.services||[]).slice().sort((a,b)=>(prefs.includes(String(b.no))?1:0)-(prefs.includes(String(a.no))?1:0)).slice(0,10);return `<article class="card stop-card ${compact?'compact-stop':''}" data-stop="${esc(stop.code)}"><div class="stop-top"><div><div class="stop-name">${esc(stop.name)}</div><div class="stop-code">Stop ${esc(stop.code)}${stop.roadName?` · ${esc(stop.roadName)}`:''}</div></div><div class="stop-actions">${stop.distance!=null?`<div class="distance">${stop.distance<1000?stop.distance+' m':(stop.distance/1000).toFixed(1)+' km'}</div>`:''}<button class="favorite-stop ${saved?'saved':''}" type="button" data-code="${esc(stop.code)}" aria-label="${saved?'Remove':'Save'} bus stop ${esc(stop.code)}">${saved?'★':'☆'}</button></div></div>${saved?`<div class="service-pref-note">${prefs.length?`Pinned services: ${prefs.map(esc).join(', ')}`:'Tap the pin on a service to prioritize it in Next Up.'}</div>`:''}<div class="services">${services.map(s=>{const pinned=prefs.includes(String(s.no));return `<div class="service ${pinned?'pinned':''}"><button class="pin-service ${pinned?'active':''}" type="button" data-stop="${esc(stop.code)}" data-service="${esc(s.no)}" aria-label="${pinned?'Unpin':'Pin'} bus ${esc(s.no)}">${pinned?'★':'＋'}</button><div class="service-no">${esc(s.no)}</div><div class="eta">${s.eta?.[0]??'—'} <small>min</small></div><div class="load">${loadText(s.load?.[0])}</div></div>`}).join('')||'<span class="distance">No estimated arrivals right now.</span>'}</div></article>`}
function renderNearby(){const stops=state.nearby?.stops||[];$('#nearbyStops').innerHTML=stops.map(s=>renderStop(s)).join('')||'<div class="card empty">Use your location to automatically find nearby bus stops.</div>';sourceLabel();renderMapMarkers();renderNextUp()}
function renderSavedStops(){const el=$('#savedStops');$('#savedStopCount').textContent=String(state.savedStops.length);if(!state.savedStops.length){el.innerHTML='<div class="empty-inline">No saved bus stops yet. Add a favourite or star a nearby stop.</div>';renderMapMarkers();renderNextUp();return}const byCode=new Map(state.savedStopData.map(x=>[x.stop?.code,x]));el.innerHTML=state.savedStops.map(saved=>{const item=byCode.get(saved.code);if(item?.stop)return renderStop(item.stop,{compact:true});return `<article class="card stop-card compact-stop"><div class="stop-top"><div><div class="stop-name">${esc(saved.name||`Bus Stop ${saved.code}`)}</div><div class="stop-code">Stop ${esc(saved.code)}</div></div><button class="favorite-stop saved" type="button" data-code="${esc(saved.code)}" aria-label="Remove bus stop ${esc(saved.code)}">★</button></div><div class="empty-inline">Refreshing arrivals…</div></article>`}).join('');sourceLabel();renderMapMarkers();renderNextUp()}
function renderSavedStations(){const el=$('#savedStations');if(!el)return;$('#savedStationCount').textContent=String(state.savedRailStations.length);if(!state.savedRailStations.length){el.innerHTML='<span class="empty-inline">No favourite stations yet. Star one below.</span>';renderMapMarkers();renderNextUp();return}el.innerHTML=state.savedRailStations.map(s=>`<button class="station-chip" type="button" data-station="${esc(s.code)}"><span>${esc(s.code)}</span>${s.name?` ${esc(s.name)}`:''}</button>`).join('');renderMapMarkers();renderNextUp()}
function groupedDepartures(station){const groups=new Map();for(const d of station.departures||[]){const key=`${d.line}|${d.destination}|${d.platform||''}`;if(!groups.has(key))groups.set(key,{...d,etas:[],hasRealtime:false,hasSchedule:false});const g=groups.get(key);g.etas.push(d.minutes);if(d.realtime===true)g.hasRealtime=true;else g.hasSchedule=true}return [...groups.values()].slice(0,6)}
function renderRail(){const stations=state.rail?.stations||[];const liveAvailable=state.rail?.realtimeAvailable===true;const boardNote=state.rail?.source==='live'?(liveAvailable?'Live predictions available · scheduled service fills any gaps':'Official scheduled times · live predictions temporarily unavailable'):'';$('#railStations').innerHTML=stations.map(station=>{const code=station.codes?.[0]||station.id||'';const saved=isRailSaved(code);return `<article class="card rail-card" data-station="${esc(code)}"><div class="stop-top"><div><div class="stop-name">${esc(station.name)}</div><div class="stop-code">${esc((station.codes||[]).join(' · '))}</div></div><div class="stop-actions">${station.distance!=null?`<div class="distance">${station.distance<1000?station.distance+' m':(station.distance/1000).toFixed(1)+' km'}</div>`:''}<button class="favorite-station ${saved?'saved':''}" type="button" data-station-code="${esc(code)}" data-station-name="${esc(station.name)}" aria-label="${saved?'Remove':'Save'} ${esc(station.name)}">${saved?'★':'☆'}</button></div></div>${boardNote?`<div class="rail-board-note">${esc(boardNote)}</div>`:''}<div class="train-list">${groupedDepartures(station).map(d=>{const mode=d.hasRealtime?'Realtime':'Scheduled';return `<div class="train-row"><div class="line-badge ${lineClass(d.line)}">${esc(d.line)}</div><div class="train-dest"><strong>${esc(d.destination)}</strong><span>${mode} · ${d.platform?`Platform ${esc(d.platform)} · `:''}${esc(d.lineName||'Train')}</span></div><div class="train-times">${d.etas.slice(0,3).map((m,i)=>`<span class="${i===0?'next':''}">${m===0?'Arr':m+'m'}</span>`).join('')}</div></div>`}).join('')||'<div class="empty-inline">No scheduled departures found in the next 90 minutes. Try Refresh; if this persists, the LTA timetable feed may be unavailable.</div>'}</div></article>`}).join('')||'<div class="card empty">Use your location, tap a favourite station, or search for an MRT/LRT station.</div>';sourceLabel();renderMapMarkers();renderNextUp()}
function allRailStationsForSummary(){const out=[];for(const s of state.rail?.stations||[])out.push(s);for(const p of state.savedRailData||[])for(const s of p?.stations||[])if(!out.some(x=>(x.codes?.[0]||x.id)===(s.codes?.[0]||s.id)))out.push(s);return out}
function departureCandidates(){const candidates=[];const seenStops=new Set();for(const item of state.savedStopData){const stop=item.stop;if(!stop)continue;seenStops.add(stop.code);const prefs=savedStopFor(stop.code)?.services||[];for(const s of stop.services||[]){if(s.eta?.[0]==null)continue;if(prefs.length&&!prefs.includes(String(s.no)))continue;candidates.push({kind:'bus',minutes:s.eta[0],label:`Bus ${s.no}`,detail:stop.name,priority:prefs.includes(String(s.no))?0:1})}}for(const stop of state.nearby?.stops||[]){if(seenStops.has(stop.code))continue;for(const s of stop.services||[]){if(s.eta?.[0]==null)continue;candidates.push({kind:'bus',minutes:s.eta[0],label:`Bus ${s.no}`,detail:stop.name,priority:2})}}for(const station of allRailStationsForSummary()){const stationCode=station.codes?.[0]||'';const saved=isRailSaved(stationCode);for(const d of station.departures||[]){if(d.minutes==null)continue;candidates.push({kind:'rail',minutes:d.minutes,label:`${d.line} → ${d.destination}`,detail:station.name,priority:saved?0:state.lat!=null?1:2})}}return candidates.sort((a,b)=>(a.priority-b.priority)||(a.minutes-b.minutes)).slice(0,6)}
function renderNextUp(){const title=$('#nextUpTitle'),copy=$('#nextUpCopy'),action=$('#nextUpAction'),options=$('#nextUpOptions');if(!title||!copy||!action||!options)return;const c=departureCandidates();if(!c.length){title.textContent='Make SGBuddy yours';copy.textContent='Allow location or save the bus stops and MRT/LRT stations you use most. SGBuddy will then prioritize the departures that matter to you.';action.textContent='Set up';options.innerHTML='';return}const first=c.slice().sort((a,b)=>a.minutes-b.minutes)[0];title.textContent=first.minutes<=3?'A departure is imminent':first.minutes<=7?'Head out soon':`Next useful departure in ${first.minutes} min`;copy.textContent=state.lat!=null?'Prioritized from nearby and saved transport.':'Prioritized from your saved stops and stations.';action.textContent=first.minutes===0?'Now':`${first.minutes} min`;options.innerHTML=c.slice(0,3).map(x=>`<div class="next-option"><span class="next-icon">${x.kind==='rail'?'▰':'▣'}</span><div><strong>${esc(x.label)}</strong><span>${esc(x.detail)}</span></div><b>${x.minutes===0?'Arr':x.minutes+'m'}</b></div>`).join('')}
function renderAlerts(){const a=[];if(state.train){if(state.train.status===2)(state.train.disruptions||[]).forEach(d=>a.push({i:'⚠',t:`${d.line||'Rail'} disruption`,c:d.message||'Service disruption'}));else a.push({i:'✓',t:'Rail network normal',c:'No major train service disruption reported.'})}if(state.traffic){(state.traffic.incidents||[]).slice(0,3).forEach(x=>a.push({i:'⌁',t:x.type||'Traffic incident',c:x.message||'Road incident reported.'}))}$('#alerts').innerHTML=a.map(x=>`<div class="card alert"><div class="alert-icon">${x.i}</div><div><div class="alert-title">${esc(x.t)}</div><div class="alert-copy">${esc(x.c)}</div></div></div>`).join('')||'<div class="card">No alerts loaded.</div>'}
function updateHero(){const w=state.weather;$('#weatherMetric').textContent=w?'☁︎':'—';$('#weatherLabel').textContent=w?.summary||'Weather';$('#railMetric').textContent=state.train?(state.train.status===2?'⚠':'✓'):'—';$('#trafficMetric').textContent=state.traffic?.count??'—';renderAlerts();sourceLabel()}
async function json(url){const r=await fetch(url);const p=await r.json();if(!r.ok)throw new Error(p.error||`Request failed ${r.status}`);return p}
async function refreshContext(){try{const [train,traffic,weather]=await Promise.all([json('/api/train'),json('/api/traffic'),json('/api/weather')]);Object.assign(state,{train,traffic,weather});updateHero()}catch(e){toast(e.message)}}
async function loadNearby(lat,lon){const busPromise=json(`/api/nearby?lat=${lat}&lon=${lon}`).then(p=>{state.nearby=p;renderNearby()}).catch(e=>toast('Bus: '+e.message));const railPromise=json(`/api/rail?lat=${lat}&lon=${lon}`).then(p=>{state.rail=p;renderRail()}).catch(e=>toast('MRT: '+e.message));await Promise.all([busPromise,railPromise]);renderNextUp()}
function setLocationStatus(text){const el=$('#locationStatus');if(el)el.textContent=text}
function closeLocationSheet(){$('#locationSheet')?.classList.add('hidden')}
function showLocationSheet(){if(!navigator.geolocation)return;$('#locationSheet')?.classList.remove('hidden')}
async function locate({interactive=true}={}){if(!navigator.geolocation){setLocationStatus('Location is not supported on this device');if(interactive)toast('Location is not supported on this device.');return false}$('#placeLabel').textContent='Locating…';setLocationStatus('Finding nearby transport…');return new Promise(resolve=>navigator.geolocation.getCurrentPosition(async p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;state.locationChoice='granted';localStorage.setItem('sgc-location-choice','granted');$('#placeLabel').textContent='Near you';setLocationStatus('Using your current location · not stored in cloud');closeLocationSheet();await loadNearby(state.lat,state.lon);if(state.transportView==='map')fitMap();resolve(true)},err=>{state.lat=null;state.lon=null;$('#placeLabel').textContent='Singapore';if(err?.code===1){state.locationChoice='denied';localStorage.setItem('sgc-location-choice','denied');setLocationStatus('Location permission denied · searches and favourites still work')}else setLocationStatus('Could not get location · try again');if(interactive)toast(err?.code===1?'Location permission was not granted. You can still use favourites and search.':'Could not get your location. Try again in a moment.');resolve(false)},{enableHighAccuracy:false,timeout:9000,maximumAge:180000}))}
async function maybeUseLocation(){if(!navigator.geolocation){setLocationStatus('Location unavailable on this device');return false}try{if(navigator.permissions?.query){const permission=await navigator.permissions.query({name:'geolocation'});if(permission.state==='granted')return locate({interactive:false});if(permission.state==='denied'){state.locationChoice='denied';localStorage.setItem('sgc-location-choice','denied');setLocationStatus('Location permission denied · favourites still work');return false}}}catch{}if(state.locationChoice==='granted')return locate({interactive:false});if(state.locationChoice==='denied'){setLocationStatus('Location permission denied · favourites still work');return false}if(state.locationChoice==='not-now'){setLocationStatus('Location off · tap Locate any time');return false}setLocationStatus('Location can personalize nearby transport');setTimeout(showLocationSheet,350);return false}
async function fetchStop(code){return json('/api/bus?stop='+encodeURIComponent(code))}
async function checkStop(code,{scroll=true}={}){try{const p=await fetchStop(code);state.nearby={source:p.source,stops:[p.stop]};renderNearby();if(scroll)$('#nearbyStops').scrollIntoView({behavior:'smooth',block:'center'});return p}catch(e){toast(e.message);return null}}
async function checkRail(query,{scroll=true}={}){try{const p=await json('/api/rail?station='+encodeURIComponent(query));state.rail=p;renderRail();if(scroll)$('#railStations').scrollIntoView({behavior:'smooth',block:'center'});return p}catch(e){toast(e.message);return null}}
async function refreshSavedStops(){if(!state.savedStops.length){state.savedStopData=[];renderSavedStops();return}const results=await Promise.all(state.savedStops.map(async s=>{try{return await fetchStop(s.code)}catch(error){return {source:'error',stop:{code:s.code,name:s.name||`Bus Stop ${s.code}`,services:[]},error:error.message}}}));state.savedStopData=results;for(const result of results){const saved=state.savedStops.find(s=>s.code===result.stop?.code);if(saved&&result.stop?.name)saved.name=result.stop.name}persistSavedStops();renderSavedStops()}
async function refreshSavedStations(){if(!state.savedRailStations.length){state.savedRailData=[];renderSavedStations();return}const results=await Promise.all(state.savedRailStations.map(async s=>{try{return await json('/api/rail?station='+encodeURIComponent(s.code))}catch(error){return {source:'error',stations:[],error:error.message}}}));state.savedRailData=results;for(let i=0;i<results.length;i++){const station=results[i]?.stations?.[0];if(station?.name)state.savedRailStations[i].name=station.name}persistSavedStations();renderSavedStations()}
function persistSavedStops(sync=false){localStorage.setItem('sgc-bus-stops',JSON.stringify(state.savedStops.map(({code,name,services})=>({code,name,services:Array.isArray(services)?services:[]}))));if(sync)queueProfileSync()}
function persistSavedStations(sync=false){localStorage.setItem('sgc-rail-stations',JSON.stringify(state.savedRailStations));if(sync)queueProfileSync()}
async function toggleSavedStop(code){code=String(code);const idx=state.savedStops.findIndex(s=>s.code===code);if(idx>=0){state.savedStops.splice(idx,1);state.savedStopData=state.savedStopData.filter(x=>x.stop?.code!==code);persistSavedStops(true);renderSavedStops();renderNearby();toast(`Removed stop ${code}`);return}if(state.savedStops.length>=12)return toast('You can save up to 12 bus stops in this version.');let name='';try{const p=await fetchStop(code);name=p.stop?.name||'';state.savedStopData.push(p)}catch{}state.savedStops.push({code,name,services:[]});persistSavedStops(true);renderSavedStops();renderNearby();toast(`Saved stop ${code}`)}
async function toggleSavedStation(code,name=''){code=String(code||'').toUpperCase();if(!code)return;const idx=state.savedRailStations.findIndex(s=>s.code===code);if(idx>=0){state.savedRailStations.splice(idx,1);state.savedRailData=state.savedRailData.filter(p=>p?.stations?.[0]?.codes?.[0]!==code);persistSavedStations(true);renderSavedStations();renderRail();toast(`Removed ${code} from favourites`);return}if(state.savedRailStations.length>=12)return toast('You can save up to 12 MRT/LRT stations.');state.savedRailStations.push({code,name});persistSavedStations(true);try{const p=await json('/api/rail?station='+encodeURIComponent(code));state.savedRailData.push(p);const station=p.stations?.[0];if(station?.name)state.savedRailStations.find(s=>s.code===code).name=station.name}catch{}persistSavedStations(true);renderSavedStations();renderRail();toast(`Saved ${name||code}`)}
function firstRail(){let best=null;for(const station of allRailStationsForSummary()){for(const d of station.departures||[]){if(d.minutes==null)continue;if(!best||d.minutes<best.minutes)best={...d,stationName:station.name,stationCode:station.codes?.[0]||''}}return best}
function firstBus(){const x=departureCandidates().filter(x=>x.kind==='bus').sort((a,b)=>a.minutes-b.minutes)?.[0];return x?{no:String(x.label).replace(/^Bus\s+/i,''),minutes:x.minutes,stop:x.detail}:null}
function advisor(q){const text=q.toLowerCase();let reply='I can use Singapore MRT, bus, weather and disruption data. Try “When is my next train?”, “Should I leave now?” or “Is it raining?”';const rail=firstRail(),bus=firstBus();if(/next.*train|mrt.*time|train.*time/.test(text))reply=rail?`From ${rail.stationName||state.rail?.stations?.[0]?.name||'your station'}, the next ${rail.line} train towards ${rail.destination} is about ${rail.minutes} minute${rail.minutes===1?'':'s'} away${rail.platform?` from platform ${rail.platform}`:''}.`:'Search or locate an MRT station first, then I can tell you the next trains.';else if(/train|mrt|rail/.test(text))reply=state.train?.status===2?`There is a rail disruption: ${state.train.disruptions?.[0]?.message||'check the alert below.'}`:rail?`Rail service is currently normal. Your next nearby train is ${rail.line} towards ${rail.destination} in about ${rail.minutes} minutes.`:'No major train disruption is currently reported.';else if(/rain|weather|umbrella/.test(text))reply=`Current forecast: ${state.weather?.summary||'weather data is not loaded yet'}.`;else if(/leave|next.*bus|bus.*time/.test(text)){const candidates=[];if(bus)candidates.push({mode:`bus ${bus.no} at ${bus.stop}`,minutes:bus.minutes});if(rail)candidates.push({mode:`${rail.line} train`,minutes:rail.minutes});candidates.sort((a,b)=>a.minutes-b.minutes);reply=candidates[0]?`The soonest departure I can see is ${candidates[0].mode} in about ${candidates[0].minutes} minutes. ${candidates[0].minutes<=5?'I would head out now.':'You have a little time, but refresh before leaving.'}`:'Locate yourself or save/search a stop first, then I can make that call.'}$('#advisorReply').textContent=reply}
function setMode(mode,sync=true){state.mode=mode;localStorage.setItem('sgc-mode',mode);$('#modeText').textContent=mode==='traveller'?'Traveller':'Resident';$('#travellerPanel').classList.toggle('hidden',mode!=='traveller');$('#modeButton .dot').style.background=mode==='traveller'?'#79a7ff':'';updateHotelButton();if(sync)queueProfileSync()}
function initPlaces(){for(const key of ['home','work','hotel'])$(`#${key}Input`).value=state.places[key]||'';updateHotelButton()}
function savePlaces(){state.places={home:$('#homeInput').value.trim(),work:$('#workInput').value.trim(),hotel:$('#hotelInput').value.trim()};cachePreferences(true);updateHotelButton();queueProfileSync();toast('Places saved — syncing to your SGBuddy profile')}
function updateHotelButton(){$('#goHotelButton').disabled=!state.places.hotel}
function openTransit(destination,origin=''){if(!destination)return toast('Add a destination first.');const u=new URL('https://www.google.com/maps/dir/');u.searchParams.set('api','1');u.searchParams.set('destination',destination);u.searchParams.set('travelmode','transit');if(origin)u.searchParams.set('origin',origin);window.open(u.toString(),'_blank','noopener')}

function ensureMap(){if(state.map)return true;if(!window.L){$('#transportMap').innerHTML='<div class="map-unavailable">Map library could not load. Bus/MRT cards still work normally.</div>';return false}state.map=L.map('transportMap',{zoomControl:true,attributionControl:true}).setView([1.3521,103.8198],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);state.mapLayer=L.layerGroup().addTo(state.map);return true}
function mapPointKey(p){return `${p.type}:${p.code||p.name}:${Number(p.lat).toFixed(5)}:${Number(p.lon).toFixed(5)}`}
function collectMapPoints(){const pts=[];for(const item of state.savedStopData){const s=item.stop;if(Number.isFinite(Number(s?.lat))&&Number.isFinite(Number(s?.lon)))pts.push({type:'saved',name:s.name,code:s.code,lat:Number(s.lat),lon:Number(s.lon)})}for(const s of state.nearby?.stops||[]){if(Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lon)))pts.push({type:isSaved(s.code)?'saved':'bus',name:s.name,code:s.code,lat:Number(s.lat),lon:Number(s.lon)})}for(const s of state.rail?.stations||[]){if(Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lon)))pts.push({type:'rail',name:s.name,code:(s.codes||[]).join(' · '),lat:Number(s.lat),lon:Number(s.lon)})}const unique=new Map();for(const p of pts){const k=p.type==='saved'?`bus:${p.code}`:mapPointKey(p);if(!unique.has(k)||p.type==='saved')unique.set(k,p)}return [...unique.values()]}
function markerStyle(type){if(type==='saved')return {radius:9,color:'#07111f',weight:3,fillColor:'#ffd166',fillOpacity:1};if(type==='rail')return {radius:8,color:'#07111f',weight:3,fillColor:'#79a7ff',fillOpacity:1};return {radius:7,color:'#07111f',weight:3,fillColor:'#63e6be',fillOpacity:1}}
function renderMapMarkers(){if(!state.map)return;state.mapLayer.clearLayers();const points=collectMapPoints();for(const p of points){L.circleMarker([p.lat,p.lon],markerStyle(p.type)).bindPopup(`<strong>${esc(p.name)}</strong><br>${esc(p.code||'')}${p.type==='rail'?'<br>MRT/LRT station':'<br>Bus stop'}`).addTo(state.mapLayer)}if(Number.isFinite(state.lat)&&Number.isFinite(state.lon))L.circleMarker([state.lat,state.lon],{radius:7,color:'#fff',weight:3,fillColor:'#ff7b8a',fillOpacity:1}).bindPopup('You are here').addTo(state.mapLayer)}
function fitMap(){if(!ensureMap())return;renderMapMarkers();const coords=collectMapPoints().map(p=>[p.lat,p.lon]);if(Number.isFinite(state.lat)&&Number.isFinite(state.lon))coords.push([state.lat,state.lon]);setTimeout(()=>{state.map.invalidateSize();if(coords.length===1)state.map.setView(coords[0],16);else if(coords.length>1)state.map.fitBounds(coords,{padding:[28,28],maxZoom:16});else state.map.setView([1.3521,103.8198],11)},50)}
function setTransportView(view){state.transportView=view==='map'?'map':'cards';localStorage.setItem('sgc-transport-view',state.transportView);$('#cardsView').classList.toggle('hidden',state.transportView==='map');$('#mapView').classList.toggle('hidden',state.transportView!=='map');$('#cardsViewButton').classList.toggle('active',state.transportView==='cards');$('#mapViewButton').classList.toggle('active',state.transportView==='map');if(state.transportView==='map')fitMap()}

$('#locateButton').addEventListener('click',locate);
$('#refreshButton').addEventListener('click',async()=>{await Promise.all([refreshContext(),refreshSavedStops()]);if(state.lat!=null&&state.lon!=null)await loadNearby(state.lat,state.lon);else{if(state.rail?.stations?.[0]?.codes?.[0])await checkRail(state.rail.stations[0].codes[0]);if(state.nearby?.stops?.[0]?.code)await checkStop(state.nearby.stops[0].code)}toast('Refreshed')});
$('#stopForm').addEventListener('submit',e=>{e.preventDefault();const c=$('#stopInput').value.trim();if(!/^\d{5}$/.test(c))return toast('Enter a 5-digit bus stop code.');checkStop(c)});
$('#savedStopForm').addEventListener('submit',async e=>{e.preventDefault();const c=$('#savedStopInput').value.trim();if(!/^\d{5}$/.test(c))return toast('Enter a 5-digit bus stop code.');$('#savedStopInput').value='';if(isSaved(c))return toast(`Stop ${c} is already saved.`);await toggleSavedStop(c)});
$('#railForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#railInput').value.trim();if(!q)return toast('Enter a station name or code.');checkRail(q)});
document.addEventListener('click',e=>{const b=e.target.closest('.favorite-stop');if(b)toggleSavedStop(b.dataset.code)});
$('#cardsViewButton').addEventListener('click',()=>setTransportView('cards'));$('#mapViewButton').addEventListener('click',()=>setTransportView('map'));$('#fitMapButton').addEventListener('click',fitMap);
$('#advisorForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#advisorInput').value.trim();if(q)advisor(q)});$$('.chips button').forEach(b=>b.addEventListener('click',()=>advisor(b.dataset.q)));
$('#modeButton').addEventListener('click',()=>setMode(state.mode==='resident'?'traveller':'resident'));$('#navTravel').addEventListener('click',()=>{setMode('traveller');$('#travellerPanel').scrollIntoView({behavior:'smooth'})});$('#navFreya').addEventListener('click',()=>$('#advisorInput').focus());$('#navTransport').addEventListener('click',()=>$('.transport-heading').scrollIntoView({behavior:'smooth'}));
$('#savePlaces').addEventListener('click',savePlaces);$$('.quick-destinations button').forEach(b=>b.addEventListener('click',()=>{const value=state.places[b.dataset.place]||'';if(!value)return toast(`Save your ${b.dataset.place} first.`);$('#tripTo').value=value}));$('#planTrip').addEventListener('click',()=>openTransit($('#tripTo').value.trim(),$('#tripFrom').value.trim()));$('#goHotelButton').addEventListener('click',()=>openTransit(state.places.hotel));
$('#installButton').addEventListener('click',installApp);$('#closeInstallSheet').addEventListener('click',closeInstallSheet);$('#installSheet').addEventListener('click',e=>{if(e.target===$('#installSheet'))closeInstallSheet()});
$('#syncProfileButton').addEventListener('click',()=>syncProfileNow());$('#linkDeviceButton').addEventListener('click',showPairPanel);$('#copyPairLinkButton').addEventListener('click',copyPairLink);$('#closePairPanelButton').addEventListener('click',()=>$('#pairPanel').classList.add('hidden'));$('#exportProfileButton').addEventListener('click',exportProfile);$('#importProfileButton').addEventListener('click',()=>$('#importProfileInput').click());$('#importProfileInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(file)await importProfileFile(file);e.target.value=''});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallUi()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;updateInstallUi();toast('SGBuddy installed')});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
greet();setMode(state.mode,false);initPlaces();setTransportView(state.transportView);updateInstallUi();renderSavedStops();initCloudProfile();refreshContext();checkRail('EW4');checkStop('84009');
