import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
const read=p=>fs.readFileSync(p,'utf8');
const ui=read('app-v130.js'),app=read('app-v090.js'),html=read('index.html'),sw=read('sw.js');
const seed=JSON.parse(read('data/discover-v120.json')),published=JSON.parse(read('data/facts-published.json'));
const approved=JSON.parse(read('content/facts-approved.json'));
assert.ok(app.includes("import('/app-v130.js')"),'buddy module missing from app bootstrap');
assert.ok(html.includes('buddy-v130.css'),'buddy stylesheet not loaded');
assert.ok(sw.includes('/app-v130.js')&&sw.includes('/data/facts-published.json'),'PWA missing assets');
for(const v of ['buddyLauncher','buddyPanel','buddyAskForm','buddyReply','sgbFactList','sgbFactQuery','sgbFactTopic'])assert.ok(ui.includes(v),'missing '+v);
for(const mode of ['resident','visitor','executive','student'])assert.ok(seed.facts.some(f=>f.modes.includes(mode)));
assert.equal(published.verifiedCount,published.facts.length);
assert.ok(approved.length>=29);
assert.ok(approved.every(f=>f.status!=='verified'),'Seed facts should not be silently promoted');
const scratch='data/_facts-test-output.json';
let result=spawnSync(process.execPath,['scripts/publish-facts.mjs','content/facts-approved.json',scratch],{encoding:'utf8'});
assert.equal(result.status,0,result.stderr);
const parsed=JSON.parse(read(scratch));
assert.equal(parsed.verifiedCount,0,'Unreviewed facts were incorrectly published');
fs.unlinkSync(scratch);
console.log('Wave 4+5 checks passed: staged claims blocked; 2D buddy and persona-aware fact library wired.');
